### ISSUE TITLE
Single field selector should return array of values

### ISSUE THREAD

**Issue by kodart** [skyscreamer/yoga#207]
Entities:
{"id":1, "name":"abc"}, {"id":2, "name":"bbb"}

Analogy: Ruby on Rails, pluck(:name) returns ["abc", "bbb"]

At the moment single field selector returns an array of objects:
?selector=name returns

[{"name": "abc"}, {"name": "bbb"}]

Response has too much unnecessary data. At least there should be a way to compact data.

**Comment by kodart** [comment]
Any comments? Is it something people need?

**Comment by carterpage** [comment]
The main issue is client consistency/extensibility.  If a developer is programming something to iterate through an array [ "abc", "bbb" ], then they decide they want the id, they need to reprogram the code that parses out the names.  Likewise, I might be grabbing ids and names, then realize my code doesn't really use the names, so I remove them from the selector.  Again I would have to reprogram my client.  This might sound trivial, since it's a trivial example, but it could cause some surprising errors on complicated systems.

If the issue is performance, speed is going to be bound by storage I/O, CPU, and request latency.  Network bandwidth for this sort of data is not typically going to be a bottleneck, particularly if the connection is running gzip compression.  Compression gets fantastic ratios on the repeating strings of JSON.
