### ISSUE TITLE
Style the Selector Navigator

### ISSUE THREAD

**Issue by sduskis** [skyscreamer/yoga#92]

**Comment by carterpage** [comment]
Finally found a way to replicate the Heisenbug in here:
1. Add a one-second sleep to MetaDataController.getTypeMetaData
2. Open up the selector builder: http://yoga.skyscreamer.org/user/2.yoga
3. Quickly click these in succession: recommendedAlbums, friends, favoriteArtists

After they open one of them will have broken children.

It is caused by a race-condition, which sometimes causes _get_node to return an unexpected value:

https://github.com/skyscreamer/yoga/blob/master/yoga-demos/yoga-demo-springmvc/src/main/webapp/selectorBuilder.html#L142
